// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1RIQrYiGu9zQ8s0qC5Ajy2OzCjGbHmBU',
    appId: '1:150794647390:web:086c4912c3f594d5b201cf',
    messagingSenderId: '150794647390',
    projectId: 'bwa-cozy-59609',
    authDomain: 'bwa-cozy-59609.firebaseapp.com',
    storageBucket: 'bwa-cozy-59609.appspot.com',
    measurementId: 'G-485YPM56QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUcnesUM9PTeRtgPpP3eqjzZDu_X8ZOE8',
    appId: '1:150794647390:android:2c1c17e15187ecb8b201cf',
    messagingSenderId: '150794647390',
    projectId: 'bwa-cozy-59609',
    storageBucket: 'bwa-cozy-59609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8A8tu6tTxNNjCeJK4-3P31kSaj3rRVS0',
    appId: '1:150794647390:ios:1099c50478fa28b7b201cf',
    messagingSenderId: '150794647390',
    projectId: 'bwa-cozy-59609',
    storageBucket: 'bwa-cozy-59609.appspot.com',
    iosClientId: '150794647390-85njcr4cughu2tc9sf84ajcdv1fj7jgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwaCozy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8A8tu6tTxNNjCeJK4-3P31kSaj3rRVS0',
    appId: '1:150794647390:ios:a2d5368fee40640fb201cf',
    messagingSenderId: '150794647390',
    projectId: 'bwa-cozy-59609',
    storageBucket: 'bwa-cozy-59609.appspot.com',
    iosClientId: '150794647390-kh77vuobp3mfuarh20a0r2vfrsr0e9jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwaCozy.RunnerTests',
  );
}
